version: '3.7'
services: 
    frontend:
        image: raharisonl/nginx
        ports: 
            - "80:80"
        depends_on: 
            - backend
    
    backend:
        image: raharisonl/node-web-app
        ports: 
            - "8081:8081"